# Generated by Django 5.1.7 on 2025-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='details',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='user_history/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
