# Generated by Django 5.1.7 on 2025-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0004_remove_userhistory_details_userhistory_media_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='media_file',
            new_name='media',
        ),
    ]
