# Generated by Django 5.1.7 on 2025-03-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0005_rename_media_file_userhistory_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
