# Generated by Django 5.1.7 on 2025-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0006_userhistory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flutterwave_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='flutterwave_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='flutterwave_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
