# Generated by Django 5.1.7 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0007_user_flutterwave_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='sample_audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
