# Generated by Django 5.1.7 on 2025-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailAuth', '0008_alter_voice_sample_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
